# Generated by Django 4.0.3 on 2022-07-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p9_livre', '0004_remove_review_body_remove_review_headline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
