# Generated by Django 4.0.3 on 2022-07-28 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p9_livre', '0005_ticket_rating_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(related_name='like_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='likes',
            field=models.ManyToManyField(related_name='like_ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
